In [1]:
import pandas as pd
import xgboost as xgb
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from IPython.display import display
import matplotlib.pyplot as plt
import numpy as np

In [10]:
#data = pd.read_csv('resources/leagues/epl2018.csv')
data = pd.read_csv('resources/leagues/laliga2018.csv')
data = data.drop(columns=['Unnamed: 0'])
display(data.head())

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,SP1,18/08/17,Leganes,Alaves,1,0,H,1,0,H,...,1.46,18,-0.50,2.07,2.03,1.90,1.86,1.98,3.35,4.63
1,SP1,18/08/17,Valencia,Las Palmas,1,0,H,1,0,H,...,2.27,16,-0.75,2.05,1.97,1.96,1.91,1.78,4.24,4.43
2,SP1,19/08/17,Celta,Sociedad,2,3,A,1,1,D,...,1.84,18,-0.25,2.08,2.05,1.87,1.83,2.12,3.53,3.74
3,SP1,19/08/17,Girona,Ath Madrid,2,2,D,2,0,H,...,1.74,16,1.25,1.77,1.75,2.25,2.16,6.93,3.83,1.63
4,SP1,19/08/17,Sevilla,Espanol,1,1,D,1,1,D,...,2.09,16,-1.00,2.12,2.06,1.86,1.82,1.64,4.18,5.82

In [15]:
#data['Date'].value_counts()
data.loc[:,['HomeTeam','AwayTeam','FTR','FTHG','FTAG',]]
data["HomeTeam"].value_counts()
# data['Date'].value_counts()
# data.loc[:,['Date','HomeTeam','AwayTeam','FTHG','FTAG','FTR']].set_index("Date")
# data.loc[data.AwayTeam=='Leganes']

Sevilla        19
Valencia       19
Getafe         19
Barcelona      19
Espanol        19
Betis          19
Leganes        19
Celta          19
La Coruna      19
Ath Madrid     19
Real Madrid    19
Las Palmas     19
Malaga         19
Levante        19
Ath Bilbao     19
Girona         19
Villarreal     19
Eibar          19
Alaves         19
Sociedad       19
Name: HomeTeam, dtype: int64

In [19]:
#What is the win rate for the home team
n_matches = data.shape[0]
#n_matches
n_features = data.shape[1] - 1
#n_features
n_homewins = len((data.FTR =='H'))
win_rate = (float(n_matches)/(n_features))*100

print ("Total number of matches: {}".format(n_matches))
print ("Total number of features:{}".format(n_features))
print ("Number of matchess won by home team :{}".format(n_homewins))
print ("Winrate of home team:{:.2f}%".format(win_rate))

Total number of matches: 380
Total number of features:63
Number of matchess won by home team :380
Winrate of home team:603.17%